title: "Abishek P.Y"
email: abigochat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a computer science student intrested in web development
baseurl: "/" 
url: "abishek.is-a.dev" 
twitter_username: abishek_py
github_username:  vj-abishek

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
